#!/usr/bin/env python3
"""
gen_permissions_md.py — generate PERMISSIONS.md from the permissions schema
plus the active tenant's title mapping.

Schema lives at: config/permissions.schema.yaml
Tenant titles at: config/tenants/<TENANT_ID>/titles.yaml

Run from project root:
    TENANT_ID=firstline-schools python tools/gen_permissions_md.py

Outputs to PERMISSIONS.md (overwrites). Review the diff before committing.
This is a one-shot script; it does NOT run automatically.
"""
import os
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML not installed. Run: pip install PyYAML==6.0.2")

ROOT = Path(__file__).resolve().parent.parent
SCHEMA_PATH = ROOT / 'config' / 'permissions.schema.yaml'
TENANT_ID = os.environ.get('TENANT_ID', 'firstline-schools')
TITLES_PATH = ROOT / 'config' / 'tenants' / TENANT_ID / 'titles.yaml'
MD_PATH = ROOT / 'PERMISSIONS.md'


def merge_titles(schema: dict, titles: dict) -> dict:
    """Inject titles_keyword / titles_exact from titles.yaml into schema tiers."""
    if not titles:
        return schema
    by_id = {t['id']: t for t in (titles.get('tiers') or [])}
    merged = dict(schema)
    out_tiers = []
    for tier in (schema.get('tiers') or []):
        t = dict(tier)
        extra = by_id.get(t.get('id'), {})
        if extra.get('titles_keyword'):
            t['titles_keyword'] = extra['titles_keyword']
        if extra.get('titles_exact'):
            t['titles_exact'] = extra['titles_exact']
        out_tiers.append(t)
    merged['tiers'] = out_tiers
    return merged

SCOPE_LABEL = {
    'all_schools':  ('✅', 'All'),
    'own_school':   ('🟡', 'Own school'),
    'own_downline': ('🟡', 'Own team'),
    'self':         ('🟡', 'Self only'),
}


def fmt_scope(scope: str, note: str | None = None) -> str:
    icon, label = SCOPE_LABEL.get(scope, ('❓', scope))
    s = f"{icon} {label}"
    if note:
        s += f"<br><small>_{note}_</small>"
    return s


def fmt_blocked(explicit: bool) -> str:
    return '⛔ excluded' if explicit else '⛔'


def render(spec: dict) -> str:
    tiers = spec.get('tiers', [])
    capabilities = spec.get('capabilities', [])

    lines = []
    lines.append('# ObservationPoint — Permissions')
    lines.append('')
    lines.append('> **Auto-generated** by `tools/gen_permissions_md.py` from')
    lines.append(f'> `config/permissions.schema.yaml` + `config/tenants/{TENANT_ID}/titles.yaml`.')
    lines.append('> Do NOT edit this file directly. Edit the source YAML files and re-run.')
    lines.append('')
    lines.append(f'**Tenant:** `{TENANT_ID}`')
    lines.append('')
    lines.append('---')
    lines.append('')

    # ── Tiers ─────────────────────────────────────────────────────────────
    lines.append('## Tiers')
    lines.append('')
    for t in tiers:
        lines.append(f"### {t.get('label', t['id'])}")
        lines.append('')
        lines.append(f"`{t['id']}`")
        lines.append('')
        desc = (t.get('description') or '').strip()
        if desc:
            lines.append(desc)
            lines.append('')
        if t.get('rule'):
            lines.append(f"**Rule:** {t['rule'].strip()}")
            lines.append('')
        if t.get('titles_keyword'):
            kws = ', '.join(f"`{k}`" for k in t['titles_keyword'])
            lines.append(f"**Titles (keyword match):** {kws}")
            lines.append('')
        if t.get('titles_exact'):
            for title in t['titles_exact']:
                lines.append(f"- {title}")
            lines.append('')
        if t.get('note'):
            lines.append('> ⚠️ **Note:** ' + t['note'].strip().replace('\n', ' '))
            lines.append('')

    # ── Capabilities matrix ───────────────────────────────────────────────
    lines.append('---')
    lines.append('')
    lines.append('## Capability × Tier Matrix')
    lines.append('')

    header = '| Capability | ' + ' | '.join(t.get('label', t['id']) for t in tiers) + ' |'
    sep    = '|' + ('---|' * (len(tiers) + 1))
    lines.append(header)
    lines.append(sep)

    for cap in capabilities:
        grants_by_tier = {g['tier']: g for g in cap.get('grants', [])}
        excluded = set(cap.get('excluded_explicitly', []))
        cells = []
        for t in tiers:
            g = grants_by_tier.get(t['id'])
            if g:
                cells.append(fmt_scope(g.get('scope', ''), g.get('note')))
            else:
                cells.append(fmt_blocked(t['id'] in excluded))
        row = f"| **{cap.get('label', cap['id'])}**<br><small>`{cap['id']}`</small> | " + ' | '.join(cells) + ' |'
        lines.append(row)

    lines.append('')
    lines.append('**Legend:** ✅ All schools/staff · 🟡 Scoped (own school / own team / self) · ⛔ No access · ⛔ excluded = blocked even if user matches a higher tier (e.g., Content Leads explicitly excluded from PMAP).')
    lines.append('')

    return '\n'.join(lines) + '\n'


def main() -> int:
    if not SCHEMA_PATH.exists():
        print(f"ERROR: {SCHEMA_PATH} not found", file=sys.stderr)
        return 1
    with SCHEMA_PATH.open(encoding='utf-8') as f:
        schema = yaml.safe_load(f)
    titles = {}
    if TITLES_PATH.exists():
        with TITLES_PATH.open(encoding='utf-8') as f:
            titles = yaml.safe_load(f) or {}
    else:
        print(f"WARN: {TITLES_PATH} not found — generated doc will lack title lists.")
    spec = merge_titles(schema, titles)
    md = render(spec)
    MD_PATH.write_text(md, encoding='utf-8')
    print(f"Wrote {MD_PATH} ({len(md)} bytes, {md.count(chr(10))} lines)")
    print(f"Tenant: {TENANT_ID} · Tiers: {len(spec.get('tiers', []))} · Capabilities: {len(spec.get('capabilities', []))}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
